#!/usr/bin/env bash
# update_cores.sh — Replicates update_cores.ipy from Lemuroid
#
# Generates the list of available libretro cores for Android by checking
# buildbot.libretro.com nightly builds and the LemuroidCores GitHub repo.
#
# Usage: ./update_cores.sh [CORES_VERSION]
#   CORES_VERSION defaults to the value in CORES_VERSION file.
#
# Output: updates CORES_VERSION file and prints available core names.
#
# Requires: curl, jq (optional, for JSON parsing)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORES_VERSION="${1:-$(cat "$SCRIPT_DIR/CORES_VERSION" 2>/dev/null || echo "1.17.0")}"

echo "=== SwtFrontend Core Updater ==="
echo "Cores version: $CORES_VERSION"
echo ""

# Known cores from Lemuroid (matching CoreID.kt enum in retrograde-app-shared)
# These are the cores available at https://github.com/Swordfish90/LemuroidCores
KNOWN_CORES=(
    "stella"
    "fceumm"
    "snes9x"
    "genesis_plus_gx"
    "gambatte"
    "mgba"
    "mupen64plus_next"
    "pcsx_rearmed"
    "ppsspp"
    "fbneo"
    "mame2003_plus"
    "desmume"
    "melonds"
    "handy"
    "mednafen_pce_fast"
    "prosystem"
    "mednafen_ngp"
    "mednafen_wswan"
    "citra"
    "dosbox_pure"
)

# Supported Android ABIs
ABIS=("arm64-v8a" "armeabi-v7a" "x86_64" "x86")

# Verify cores availability on GitHub
BASE_URL="https://github.com/Swordfish90/LemuroidCores/raw/${CORES_VERSION}"

echo "Checking core availability for version $CORES_VERSION..."
echo ""

AVAILABLE_CORES=()
MISSING_CORES=()

for core in "${KNOWN_CORES[@]}"; do
    SO_NAME="lib${core}_libretro_android.so"
    # Check arm64-v8a as primary indicator
    URL="${BASE_URL}/lemuroid_core_${core}/src/main/jniLibs/arm64-v8a/${SO_NAME}"
    
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -L --max-time 10 "$URL" 2>/dev/null || echo "000")
    
    if [ "$HTTP_CODE" = "200" ]; then
        AVAILABLE_CORES+=("$core")
        echo "  ✓ $core ($SO_NAME)"
    else
        MISSING_CORES+=("$core")
        echo "  ✗ $core (HTTP $HTTP_CODE)"
    fi
done

echo ""
echo "=== Summary ==="
echo "Available: ${#AVAILABLE_CORES[@]} cores"
echo "Missing:   ${#MISSING_CORES[@]} cores"

if [ ${#MISSING_CORES[@]} -gt 0 ]; then
    echo ""
    echo "Missing cores:"
    for core in "${MISSING_CORES[@]}"; do
        echo "  - $core"
    done
fi

# Update CORES_VERSION file
echo ""
echo "$CORES_VERSION" > "$SCRIPT_DIR/CORES_VERSION"
echo "Updated CORES_VERSION to $CORES_VERSION"

# Generate core list file for reference
cat > "$SCRIPT_DIR/available_cores.txt" << EOF
# Auto-generated by update_cores.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Version: $CORES_VERSION
# Available cores for Android ABIs: ${ABIS[*]}
$(printf '%s\n' "${AVAILABLE_CORES[@]}")
EOF

echo "Generated available_cores.txt"
echo ""
echo "Done! CoreUpdaterImpl will download these at runtime."
